name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
env:
  PROJECT_ID: "xenon-coast-382718"
  PROJECT_NUMBER: "41246861705"
  CLUSTER: frodo
  CLUSTER_ZONE: us-central1-c

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      
      - name: chmod gradle
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build --no-daemon
        
      - name: check build
        run: ls ./build/libs
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
      - name: docker build
        run: |
          cp ./build/libs/*.war ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicdlab:v${{ env.RELEASE_VERSION }} ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicdlab:latest ./Dockerfile
      - name: docker images check
        run: docker images
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docer push
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicdlab:v${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicdlab:latest

      - id: 'auth'
        name: 'Obtain access token by using workload identity federation'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          create_credentials_file: true
          token_format: access_token
          #workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
          workload_identity_provider: projects/412468617059/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
          #service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com\
          service_account: github-actions-workflow@xenon-coast-382718.iam.gserviceaccount.com
       
      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.CLUSTER_ZONE }}

    
#       #- name: Get GKE Credentials
#       #  uses: google-github-actions/get-gke-credentials@v0.7.0
#       #  with:
#       #    cluster_name: ${{ secrets.GKE}}
#       #    location: 	${{ secrets.GCP_Zone }}
#       #    project_id:  ${{ secrets.GCP_Project }}
#       #    credentials: ${{ secrets.GCP_SA_KEY }}
      - name: was-deploy restart
        run: kubectl set image deploy was was=${{ secrets.DOCKERHUB_USERNAME }}/cicdlab:v${{ env.RELEASE_VERSION }}
